package com.pet.model;

import java.util.List;

public interface PetDAO {
	 public int idchk(String id);
	   public int nickchk(String nick);
	   public List<BoardDTO> dogList();
	   public List<BoardDTO> catList();
	   public void adduser(memberDTO dto);
	   public int login(memberDTO dto);
	   public memberDTO getUserInfo(String id);
	   public List<BoardDTO> catgetList();
	   public List<BoardDTO> search(String field, String name);
	   public void updateUser(memberDTO dto);
	   public void deleteUser(String id);
	   public void sandamg(SangdamDTO dto);
	   public void dog_insertBoard(BoardDTO dto);
	   public void cat_insertBoard(BoardDTO dto);
	   public void free_insertBoard(BoardDTO dto);
	   public void info_insertBoard(BoardDTO dto);
	   public List<BoardDTO> dog_getList(int page,int rowsize);
	   public List<BoardDTO> cat_getList(int page,int rowsize);
	   public List<BoardDTO> free_getList(int page,int rowsize);
	   public List<BoardDTO> dogInfo_getList();
	   public List<BoardDTO> catInfo_getList();
	   public List<BoardDTO> searchBoard(String find_name);
	   public List<ProductDTO> searchProduct(String find_name);
	   public List<PlaceDTO> searchPlace(String find_name);
	   public void readCount(int no);
	   public BoardDTO content(int no);
	   public void like(int no);
	   public void unlike(int no);
	   public List<BoardDTO> dog_Best();
	   public List<BoardDTO> cat_Best();
	   public List<BoardDTO> free_Best();
	   public int dog_Count();
	   public int cat_Count();
	   public int free_Count();
	   public int dogInfo_Count();
	   public int catInfo_Count();
	   public void insertCommant(CommantDTO dto);
	   public List<CommantDTO> Commant_getList(int page, int rowsize, int ckNo);
	   public List<CommantDTO> Commant_getList123(int startNo, int endNo, int ckNo);
	   public int dogSearchCount(String find_field,String find_name);
	   public int catSearchCount(String find_field,String find_name);
	   public int freeSearchCount(String find_field,String find_name);
	   public void replyAdd(CommantDTO dto);
	   public void replyUpdate(CommantDTO dto);
	   public List<CommantDTO> test(CommantDTO dto);
	   public int testMax(CommantDTO dto);
	   public int watchOn(int grp);
	   public void updateBoard(BoardDTO dto);
	   public void photoUpdate(BoardDTO dto);
	   public void deleteBoard(BoardDTO dto);
	   public void deleteCommantAll(BoardDTO dto);
	   public void deleteCommantOne(int bno);
	   public void updateCommant(CommantDTO dto);
	   public void upchk(UpDTO dto);
	   public int chk(UpDTO dto);
	   public void downchk(UpDTO dto);
	   public void deleteBoardUp(int no);
	   public void commant_like(int no);
	   public void commant_unlike(int no);
	   public int commant_count(int no);
	   public List<BoardDTO> dogSearchList(int page,int rowsize,String find_name,String find_field);
	   public List<BoardDTO> catSearchList(int page,int rowsize,String find_name,String find_field);
	   public List<BoardDTO> freeSearchList(int page,int rowsize,String find_name,String find_field);
	   public List<PlaceDTO> getPlaceList(String place);
	   public void addPlace(PlaceDTO dto);
	   public PlaceDTO getPlaceInfo(int no);
	   public void addItem(ProductDTO dto);
	   public List<ProductDTO> getItemList();
	   public List<ProductDTO> getSelectItemList(int no);
	  
	   public List<BoardDTO> konggeelist();
	   public void insertKonggee(BoardDTO dto);
	   public List<SangdamDTO> sangdam();
	   public void deleteSangdam(String tomail);
	   public void boardWriterUpdate(String backNickName,String changeNickName);
	   public void commantWriterUpdate(String backNickName,String changeNickName);
	   public List<ProductDTO> getSelectItemRange(int no);
	   public List<ProductDTO> getPublicCateItem(int no);
	   public List<ProductDTO> getCateItem(int no);
	   public ProductDTO getItemcont(int no);
	   public int isBasket(BasketDTO dto);
	   public void addBasket(BasketDTO dto);
	   public void addUpdateBasket(BasketDTO dto);
	   public int isZzim(ZzimDTO dto);
	   public void addZzim(ZzimDTO dto);
	   public List<Integer> getMyZzim(String id);
	   public void deleteZzimItem(ZzimDTO dto);
	   public List<BasketDTO> getMyBasket(String id);
	   public void deleteBasketItem(BasketDTO dto);
	   public void changeBasketNum(BasketDTO dto);
	   public void parceloutwrite(BoardDTO dto);
	   public List<BoardDTO> getParList();
	   public List<BoardDTO> getCatParList();
	   public List<BoardDTO> getDogParList();
}
